"""add email in users table

Revision ID: 07391d6e4490
Revises: 95a6532d0272
Create Date: 2020-05-10 18:24:56.161757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07391d6e4490'
down_revision = '95a6532d0272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
